"""update tokens

Revision ID: 18ac4f26e60b
Revises: f1f6e508dca6
Create Date: 2016-07-04 12:31:27.284709

"""

# revision identifiers, used by Alembic.
revision = '18ac4f26e60b'
down_revision = 'f1f6e508dca6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
