"""update posts

Revision ID: 2c6903c4230d
Revises: d071e9167bb5
Create Date: 2016-07-05 16:33:45.525691

"""

# revision identifiers, used by Alembic.
revision = '2c6903c4230d'
down_revision = 'd071e9167bb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
