"""gravatar

Revision ID: 5e2cb065ae3d
Revises: 9a8b0f1f1e87
Create Date: 2016-07-04 18:54:18.697770

"""

# revision identifiers, used by Alembic.
revision = '5e2cb065ae3d'
down_revision = '9a8b0f1f1e87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
